default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: suplier_market_development

test:
  <<: *default
  database: suplier_market_test

production:
  <<: *default
  database: suplier_market_production
  username: suplier_market
  password: <%= ENV['SUPLIER_MARKET_DATABASE_PASSWORD'] %>
